---
name: nekos-build

on:
  # Run on pushes to any branch
  push:
  # Allow manual triggers
  workflow_dispatch:

jobs:
  build_amd64:
    name: Build NekOS (x86_64)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up GitHub runner space
        run: ./.github/gh-action-free-space.sh

      # We can't run Podman-in-Podman directly in GitHub Actions
      # without this, seemingly
      - name: Emulate Docker CLI with Podman
        run: sudo apt -y install podman-docker

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-x86_64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi

  build_arm64:
    name: Build NekOS (aarch64)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up GitHub runner space
        run: ./.github/gh-action-free-space.sh

      # We can't run Podman-in-Podman directly in GitHub Actions
      # without this, seemingly
      - name: Emulate Docker CLI with Podman
        run: sudo apt -y install podman-docker

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-aarch64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi
