---
name: nekos-build

on:
  # Run on pushes to any branch
  push:
  # Allow manual triggers
  workflow_dispatch:

jobs:
  build_amd64:
    name: Build NekOS (x86_64)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up GitHub runner space
        run: ./.github/gh-action-free-space.sh

      # This is deeply cursed and creates a frankenbuntu, but it works
      # and we need to do it to get a newer version of Podman that
      # actually supports heredocs (allows us to borrow from StageX's
      # upstream Containerfiles without rewriting them)
      #
      # The version shipped in 24.04 should support them really, but
      # Canonical have patched it out:
      #   https://github.com/containers/buildah/issues/5474#issuecomment-2058440179
      #
      # This fix can be retired when GitHub update the `ubuntu-latest`
      # runner to Ubuntu 26.04
      - name: Install Podman from Ubuntu 25.04
        run: |
          sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu plucky main universe" > /etc/apt/sources.list.d/plucky.list'
          sudo apt update
          sudo apt install -y podman conmon crun runc

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-x86_64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi

  build_arm64:
    name: Build NekOS (aarch64)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up GitHub runner space
        run: ./.github/gh-action-free-space.sh

      # Note the subtle difference between this and the amd64 version!
      #
      # For aarch64 packages, we need to use ports.ubuntu.com rather than
      # archive.ubuntu.com
      - name: Install Podman from Ubuntu 25.04
        run: |
          sudo sh -c 'echo "deb http://ports.ubuntu.com/ubuntu-ports plucky main universe" > /etc/apt/sources.list.d/plucky.list'
          sudo apt update
          sudo apt install -y podman conmon crun runc

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-aarch64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi
