---
name: nekos-build

on:
  # Run on pushes to any branch
  push:

jobs:
  build_amd64:
    name: Build NekOS (x86_64)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # We can't run Podman-in-Podman directly in GitHub Actions
      # so we need to use this community-maintained action
      - name: Emulate Docker CLI with Podman
        uses: k8s-crafts/podman-cli-action@v1

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-x86_64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi

  build_arm64:
    name: Build NekOS (aarch64)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # We can't run Podman-in-Podman directly in GitHub Actions
      # so we need to use this community-maintained action
      - name: Emulate Docker CLI with Podman
        uses: k8s-crafts/podman-cli-action@v1

      - name: Run buildscript
        run: ./build-all

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NekOS-aarch64
          path: |
            firmware/build/firmware.fd
            firmware/build/OVMF_VARS_CUSTOM.json
            uki/build/uki.efi
